name: prompting
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - accelerate==0.17.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - altair==4.2.2
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - blinker==1.5
    - blis==0.7.9
    - boto3==1.28.2
    - botocore==1.31.2
    - braceexpand==0.1.7
    - cachetools==5.3.0
    - catalogue==2.0.8
    - cffi==1.15.1
    - cfgv==3.3.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cmake==3.26.4
    - colorama==0.4.6
    - comm==0.1.2
    - confection==0.0.4
    - contexttimer==0.3.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - cymem==2.0.7
    - debugpy==1.6.6
    - decord==0.6.0
    - defusedxml==0.7.1
    - distlib==0.3.6
    - einops==0.6.0
    - entrypoints==0.4
    - executing==1.2.0
    - fairscale==0.4.4
    - fastjsonschema==2.16.3
    - filelock==3.9.0
    - fonttools==4.39.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - ftfy==6.1.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - greenlet==2.0.2
    - huggingface-hub==0.13.1
    - identify==2.5.20
    - idna==3.4
    - imageio==2.26.0
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - iopath==0.1.10
    - ipdb==0.13.13
    - ipykernel==6.21.3
    - ipython==8.11.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.3.1
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - kaggle==1.5.13
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - lazy-loader==0.1
    - librosa==0.10.0.post2
    - lit==16.0.6
    - llvmlite==0.40.1
    - lxml==4.9.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==2.0.5
    - mpmath==1.3.0
    - msgpack==1.0.5
    - multidict==6.0.4
    - murmurhash==1.0.9
    - nbclassic==0.5.3
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - networkx==3.0
    - nodeenv==1.7.0
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - numba==0.57.1
    - numpy==1.22.4
    - omegaconf==2.3.0
    - openai==0.27.8
    - opencv-python==4.8.0.74
    - opencv-python-headless==4.5.5.64
    - opendatasets==0.1.22
    - openlimit==0.2.7
    - packaging==23.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathy==0.10.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.1.1
    - plotly==5.13.1
    - pooch==1.6.0
    - portalocker==2.7.0
    - pre-commit==3.1.1
    - preshed==3.0.8
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==3.20.3
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==11.0.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.6
    - pycparser==2.21
    - pydantic==1.10.6
    - pydeck==0.8.0
    - pygments==2.14.0
    - pympler==1.0.1
    - pynvim==0.4.3
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-magic==0.4.27
    - python-slugify==8.0.1
    - pytz==2022.7.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.0.1
    - qtconsole==5.4.1
    - qtpy==2.3.0
    - redis==4.6.0
    - regex==2022.10.31
    - requests==2.28.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.3.2
    - s3transfer==0.6.1
    - sacrebleu==2.3.1
    - salesforce-lavis==1.0.2
    - scenedetect==0.6.1
    - scikit-image==0.20.0
    - scikit-learn==1.3.0
    - scipy==1.9.1
    - semver==2.13.0
    - send2trash==1.8.0
    - sentencepiece==0.1.97
    - six==1.16.0
    - smart-open==6.3.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soundfile==0.12.1
    - soupsieve==2.4
    - soxr==0.3.5
    - spacy==3.5.1
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.6
    - stack-data==0.6.2
    - streamlit==1.20.0
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.2
    - terminado==0.17.1
    - text-unidecode==1.3
    - thinc==8.1.9
    - threadpoolctl==3.1.0
    - tifffile==2023.2.28
    - tiktoken==0.4.0
    - timm==0.4.12
    - tinycss2==1.2.1
    - tokenizers==0.13.2
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchmetrics==0.9.1
    - torchvision==0.14.1
    - tornado==6.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - transformers==4.27.0.dev0
    - triton==2.0.0
    - typer==0.7.0
    - typing-extensions==4.5.0
    - tzdata==2022.7
    - tzlocal==4.2
    - uri-template==1.2.0
    - urllib3==1.26.15
    - validators==0.20.0
    - virtualenv==20.21.0
    - wasabi==1.1.1
    - watchdog==2.3.1
    - wcwidth==0.2.6
    - webcolors==1.12
    - webdataset==0.2.39
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==4.0.5
    - yarl==1.9.2
    - zipp==3.15.0
